-- 001_create_contacts.sql
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  ip_address text,            -- optional for abuse tracking (store hashed)
  user_agent text,
  source text,                -- e.g. "portfolio-website"
  created_at timestamptz default now()
);

-- Optional: table for rate-limiting counters
create table if not exists public.contact_rate_limits (
  key text primary key, -- e.g. ip:2025-11-11
  attempts int not null default 1,
  last_attempt timestamptz not null default now()
);
