create table if not exists public.contact_idempotency (
  key text primary key,
  created_at timestamptz default now()
);

create table if not exists public.contact_rate_limits (
  key text primary key,
  attempts int not null default 1,
  last_attempt timestamptz not null default now()
);

create table if not exists public.failed_emails (
  id bigint generated by default as identity primary key,
  to_email text not null,
  subject text,
  body text,
  error text,
  created_at timestamptz default now(),
  retry_count int default 0,
  last_retry timestamptz
);
