-- 004_contacts_ai_and_denylist.sql

-- add AI / admin columns to contacts
alter table if exists public.contacts
  add column if not exists is_spam boolean default false,
  add column if not exists ai_label text,
  add column if not exists ai_score double precision,
  add column if not exists auto_replied boolean default false,
  add column if not exists read boolean default false;

-- idempotency table already exists from earlier steps

-- create denylist table to store blocked ip hashes (and expiry)
create table if not exists public.ip_denylist (
  ip_hash text primary key,
  reason text,
  blocked_until timestamptz,
  created_at timestamptz default now()
);

-- create failed_emails table (if not exists; earlier migration may have it)
create table if not exists public.failed_emails (
  id bigint generated by default as identity primary key,
  to_email text not null,
  subject text,
  body text,
  error text,
  created_at timestamptz default now(),
  retry_count int default 0,
  last_retry timestamptz
);

-- indexes
create index if not exists idx_contacts_ai_score on public.contacts (ai_score desc);
create index if not exists idx_contacts_created_at on public.contacts (created_at desc);
create index if not exists idx_ip_denylist_blocked_until on public.ip_denylist (blocked_until);
